/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as IndexRouteImport } from './routes/index'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/conteudos': typeof ConteudosRoute
  '/entrar': typeof EntrarRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/sucesso': typeof SucessoRoute
  '/trocar-senha': typeof TrocarSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/conteudos': typeof ConteudosRoute
  '/entrar': typeof EntrarRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/sucesso': typeof SucessoRoute
  '/trocar-senha': typeof TrocarSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/conteudos': typeof ConteudosRoute
  '/entrar': typeof EntrarRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/sucesso': typeof SucessoRoute
  '/trocar-senha': typeof TrocarSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar'
    | '/conteudos'
    | '/entrar'
    | '/planos'
    | '/sobre'
    | '/sucesso'
    | '/trocar-senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar'
    | '/conteudos'
    | '/entrar'
    | '/planos'
    | '/sobre'
    | '/sucesso'
    | '/trocar-senha'
  id:
    | '__root__'
    | '/'
    | '/cadastrar'
    | '/conteudos'
    | '/entrar'
    | '/planos'
    | '/sobre'
    | '/sucesso'
    | '/trocar-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  ConteudosRoute: typeof ConteudosRoute
  EntrarRoute: typeof EntrarRoute
  PlanosRoute: typeof PlanosRoute
  SobreRoute: typeof SobreRoute
  SucessoRoute: typeof SucessoRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  ConteudosRoute: ConteudosRoute,
  EntrarRoute: EntrarRoute,
  PlanosRoute: PlanosRoute,
  SobreRoute: SobreRoute,
  SucessoRoute: SucessoRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
